package YAC::Model::YAC;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'YAC::Schema',

    connect_info => {
        dsn => 'dbi:SQLite:yac.db',
        user => '',
        password => '',
        on_connect_do => q{PRAGMA foreign_keys = ON},
    }
);

=head1 NAME

YAC::Model::YAC - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<YAC>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<YAC::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.43

=head1 AUTHOR

Ricardo Filipo

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
